title: Quadri Ilebiyi
logo: /IMG_65802.jpg

description: "<br> SQL | Power BI | Excel | Data Modeling | DAX <br><br> Data Analyst delivering end-to-end analytics solutions using SQL, Power BI, and Excel. Experienced in data transformation, modeling, and dashboard development to support data-driven decisions. <br><br> 🔗 LinkedIn <br> 📧 abdulquadrilebiyi@gmail.com"

theme: jekyll-theme-minimal
