title: Quadri Ilebiyi
logo: /nnnnnn.jpg

description: "<br> Business Analysis | SQL | Power BI | Excel | ETL <br><br> Business Analyst delivering end-to-end business analysis and data analytics using SQL, Power BI and Excel. Skilled in requirements gathering, data analysis, reporting and dashboard development to support data-driven decision-making."
theme: jekyll-theme-minimal
